name: Bug report
description: Report something broken
title: "fix: "
labels: ["bug"]
body:
  - type: textarea
    id: expected
    attributes:
      label: What did you expect to happen?
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: What actually happened?
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Leave blank if not obvious.
    validations:
      required: false
